#ifndef Y_FUNCTIONSP_H
#define Y_FUNCTIONSP_H

PFNGLCREATESHADERPROC glCreateShader = NULL;
PFNGLSHADERSOURCEPROC glShaderSource = NULL; //ARB too
PFNGLCOMPILESHADERPROC glCompileShader = NULL; //ARB too
PFNGLGETSHADERIVPROC glGetShaderiv = NULL;
PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog = NULL;
PFNGLCREATEPROGRAMPROC glCreateProgram = NULL;
PFNGLATTACHSHADERPROC glAttachShader = NULL;
PFNGLLINKPROGRAMPROC glLinkProgram = NULL; //ARB too
PFNGLGETPROGRAMIVPROC glGetProgramiv = NULL; //ARB too
PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog = NULL;
PFNGLDELETESHADERPROC glDeleteShader = NULL;
PFNGLGENBUFFERSPROC glGenBuffers = NULL; //ARB too
PFNGLBINDBUFFERPROC glBindBuffer = NULL; //ARB too
PFNGLBUFFERDATAPROC glBufferData = NULL; //ARB too
PFNGLBUFFERSUBDATAPROC glBufferSubData = NULL; //ARB too
PFNGLUSEPROGRAMPROC glUseProgram = NULL;
PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray = NULL; //ARB too
PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer = NULL; //ARB too
PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray = NULL; //ARB too
PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation = NULL; //ARB too
PFNGLACTIVETEXTUREPROC glActiveTexture = NULL; //ARB too
PFNGLUNIFORMMATRIX4FVPROC glUniformMatrix4fv = NULL; //ARB too
PFNGLDELETEBUFFERSPROC glDeleteBuffers = NULL; //ARB too
PFNGLDELETEPROGRAMPROC glDeleteProgram = NULL; //ARB too

#endif
